DROP TABLE IF EXISTS USER_TABLE;

CREATE TABLE USER_TABLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  surname VARCHAR(250) NOT NULL,
  birthday DATE DEFAULT NULL
);

DROP TABLE IF EXISTS SUBSCRIPTION_TABLE;

CREATE TABLE SUBSCRIPTION_TABLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_id INT NOT NULL,
  start_date DATE DEFAULT NULL,
  foreign key (user_id) references USER_TABLE(id)
);